{{- range .Values.sso.users }}
---
apiVersion: keycloak.org/v1alpha1
kind: KeycloakUser
metadata:
  name: sso-{{ .userName }}
  namespace: {{ default "rhsso" $.Values.keycloak.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  user:
    username: {{ .userName | quote }}
    firstName: {{ .firstName | quote }}
    lastName: {{ .lastName | quote }}
    email: {{ .email | quote }}
    enabled: {{ default true .enabled }}
    realmRoles:
      - {{ .realmRoles | quote }}
    clientRoles:
      account:
        - "manage-account"
      realm-management:
        - "manage-users"
  realmSelector:
    matchLabels:
      app: sso
{{- end }}
